---

services:
  app:
    image: proj:local
    container_name: rest-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./db-data/mongo/:/data/db